### ISSUE TITLE
Missing public after creating an application

### ISSUE THREAD

**Issue by oroppas** [sparckles/starfyre#122]
Hi @sansyrox,

Executing `python -m starfyre --create="my-app"` misses `public` in `my-app`.
`https://github.com/sparckles/starfyre/tree/main/test_application` has `public` but that's not the case for
`https://github.com/sparckles/create-starfyre-app`.

```
./build.sh
Absolute path of the project = /home/ryutas/packages/wasm/starfyre/tmp/my-app
This is the working directory /home/ryutas/packages/wasm/starfyre/tmp/my-app/pages ../styles/index.css
Compilation successful
File routes populated ['app']
This is the project dir path /home/ryutas/packages/wasm/starfyre/tmp/my-app
These are the file routes ['app']
This is the dist path /home/ryutas/packages/wasm/starfyre/tmp/my-app/dist
This is the store path /home/ryutas/packages/wasm/starfyre/tmp/my-app/dist/store.js
This is the js store path /home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/starfyre/js/store.js
JS file written
Python files written
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/starfyre/__main__.py", line 82, in <module>
    main()
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/starfyre/__main__.py", line 53, in main
    create_dist(file_routes=file_routes, project_dir_path=absolute_path)
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/starfyre/dist_builder.py", line 145, in create_dist
    copy_public_files(project_dir_path)
  File "/home/ryutas/packages/wasm/starfyre/venv/lib/python3.11/site-packages/starfyre/dist_builder.py", line 117, in copy_public_files
    for file in public_dir.iterdir():
  File "/usr/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ryutas/packages/wasm/starfyre/tmp/my-app/public'
```

**Comment by sansyrox** [comment]
Hey @oroppas 👋 

It should have been fixed now 😄 Thank you for the reporting the issues, I really appreciate it ✨
