### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by dtemir** [sparckles/starfyre#52]
Would love to see Dockerfile to run with Docker.

So far tried running it a couple of times, faced some small issues that would take time to understand

Rust seems to be a pre-req:
```shell
$ pip3 install starfyre
Defaulting to user installation because normal site-packages is not writeable
Collecting starfyre
  Using cached starfyre-0.4.2.tar.gz (6.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
```

Having installed Rust, there are some libraries that I'm missing:
```shell
$ ./build.sh
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/damir/Git/starfyre/starfyre/__main__.py", line 1, in <module>
    from starfyre import compile
  File "/home/damir/.local/lib/python3.8/site-packages/starfyre/__init__.py", line 7, in <module>
    from .component import Component
  File "/home/damir/.local/lib/python3.8/site-packages/starfyre/component.py", line 40, in <module>
    class Component:
  File "/home/damir/.local/lib/python3.8/site-packages/starfyre/component.py", line 48, in Component
    parentDom: js.Element = None
AttributeError: module 'js' has no attribute 'Element'
```

Running the example throws this (don't have a solution in mind, but i haven't used poetry much so that's probably an easy fix locally):
```shell
first-starfyre-app$ poetry install
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
The currently activated Python version 3.8.10 is not supported by the project (^3.10).
Trying to find and use a compatible version.

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```

**Comment by sansyrox** [comment]
Oh, this is not nice. Thanks for reporting this issue @dtemir 😄 

One question - what OS are you using?

**Comment by dtemir** [comment]
Running Ubuntu with WSL2

**Comment by sansyrox** [comment]
I suppose this is done now :D
